image: Visual Studio 2015

init:
  - git config --global core.autocrlf input

clone_folder: C:\projects\ukncbtl-testbench
shallow_clone: true

matrix:
  fast_finish: false

platform:
  - Win32

configuration:
  - Release

environment:
  matrix:
    - toolchain: msvc13

install:
  - mkdir C:\projects\ukncbtl
  - git clone --depth=1 --branch=master https://github.com/nzeemin/ukncbtl.git C:\projects\ukncbtl
  - mkdir C:\projects\ukncbtl-testbench\emubase
  - copy C:\projects\ukncbtl\emubase\*.* C:\projects\ukncbtl-testbench\emubase

build:
  project: TestBench-VS2013.sln

after_build:
  - mkdir C:\projects\ukncbtl-testbench\temp
  - Release\TestBench-VS2013.exe

